Repository pyinat/pyinaturalist, pull requests merged in 2020-09, with the labels that each got.

#51 Add basic projects endpoints from Node API
  HISTORY.rst
  pyinaturalist/api_docs.py
  pyinaturalist/api_requests.py
  pyinaturalist/constants.py
  pyinaturalist/node_api.py
  pyinaturalist/request_params.py
  pyinaturalist/rest_api.py
  test/sample_data/get_projects.json
  test/sample_data/get_projects_by_id.json
  test/test_node_api.py
  test/test_request_params.py
Labels: new endpoint

#54 Add sample response data to Sphinx docs
  .gitignore
  HISTORY.rst
  README.rst
  docs/_static/collapsible_container.css
  docs/_templates/page.html
  docs/conf.py
  pyinaturalist/node_api.py
  pyinaturalist/rest_api.py
  test/sample_data/create_observation_fail.json
  test/sample_data/create_observation_result.json
  test/sample_data/get_nonexistent_observation.json
  test/sample_data/get_observation_fields_page1.json
  test/sample_data/get_observation_fields_page2.json
  test/sample_data/get_observations.js
  test/sample_data/get_taxa_autocomplete.json
  test/sample_data/get_taxa_autocomplete_minified.json
  test/sample_data/put_observation_field_value_result.json
  test/sample_data/update_observation_result.json
  test/test_node_api.py
  test/test_rest_api.py
Labels: docs

#55 Added observations/species_counts endpoint
  HISTORY.rst
  pyinaturalist/api_docs.py
  pyinaturalist/node_api.py
  test/sample_data/get_all_observation_species_counts_ex_results.json
  test/sample_data/get_all_observation_species_counts_page1.json
  test/sample_data/get_all_observation_species_counts_page2.json
  test/test_node_api.py
Labels: new endpoint

#56 Add sample response data for remaining endpoints
  docs/Makefile
  pyinaturalist/node_api.py
  pyinaturalist/request_params.py
  pyinaturalist/rest_api.py
  test/sample_data/add_photo_to_observation.json
  test/sample_data/get_all_observation_fields.json
  test/sample_data/get_observations_node_page1.json
  test/sample_data/get_observations_node_page2.json
  test/test_node_api.py
  test/test_rest_api.py
Labels: docs

#61 Fix issue with @document_request_params and duplicate keyword arguments
  README.rst
  pyinaturalist/api_docs.py
  pyinaturalist/constants.py
  pyinaturalist/forge_utils.py
  pyinaturalist/node_api.py
  pyinaturalist/request_params.py
  pyinaturalist/rest_api.py
  test/test_request_params.py
  test/test_rest_api.py
Labels: bug
