Repository pyinat/pyinaturalist, pull requests merged in 2024-01, with the labels that each got.

#538 Fix KeyError when using create_observation() in dry-run mode
  HISTORY.md
  pyinaturalist/session.py
  test/test_session.py
  test/v1/test_observations.py
  test/v2/test_observations_v2.py
Labels: bug

#539 Increase default timeout to 20 seconds
  HISTORY.md
  docs/user_guide/advanced.md
  docs/user_guide/client.md
  pyinaturalist/constants.py
  test/test_session.py
Labels: docs

#544 Update users.py
  pyinaturalist/v1/users.py
Labels: docs

#546 Add function to validate token
  HISTORY.md
  README.md
  docs/user_guide/advanced.md
  docs/user_guide/authentication.md
  docs/user_guide/index.md
  examples/observation_photo_metadata.py
  pyinaturalist/auth.py
  test/test_auth.py
Labels: enhancement

#547 Drop support for python 3.7
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .pre-commit-config.yaml
  LICENSE
  docs/conf.py
  docs/user_guide/general.md
  noxfile.py
  poetry.lock
  pyinaturalist/models/lazy_property.py
  pyproject.toml
Labels: logistics
